version: 2
jobs:
  test:
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: sudo pip install --upgrade pip
      - run: sudo pip install 'pipenv==2018.11.26'
      - restore_cache:
          key: 'dependency-cache-{{ .Branch }}-{{ checksum "Pipfile.lock" }}'
      - run:
          name: Install dependencies
          command: pipenv install --dev
      - run: make test


workflows:
  version: 2
  test_and_build:
    jobs:
      - test
